name: Jonathan John Thomas
#change name
markdown: kramdown

permalink: /blog/:year/:month/:day/:title 

#for RSS Feed
plugins:
  - jekyll-feed
description: Welcome to my Profile!
author: Jonathan John Thomas

